# Build and test
jobs:
  build: 
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Run tests
      run: npm test
      

# Separate deploy job  
deploy:
  needs: build
  runs-on: self-hosted

  steps:  
  - name: Deploy
    run: |
      ssh user@server 'cd app && git pull origin main && npm install && pm2 reload all'


