name: Node.js CI and Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.10.0]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          path/to/your/build/directory

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - name: Download Build Artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-artifacts
        path: cd /home/vigor-victorlee/actions-runner/_work/mi-suria/mi-suria
    - name: Deploy Application
      run: |
        # Your deployment commands here
        # For example, if using PM2 to manage node processes:
        cd cd /home/vigor-victorlee/actions-runner/_work/mi-suria/mi-suria
        pm2 reload ecosystem.config.js
