name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.10.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    env: 
      APP_URL: ${{secrets.APP_URL}}
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      NEXT_PUBLIC_SUPABASE_URL: ${{secrets.NEXT_PUBLIC_SUPABASE_URL}}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY}}
      NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${{secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}}
      SERVICE_ROLE: ${{secrets.SERVICE_ROLE}}

    

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Change Directory
      run: cd /home/vigor-victorlee/actions-runner/_work/mi-suria/mi-suria
    - run: pm2 reload all